#!/usr/bin/env bash

## Wrapper command for fin pull files that resets permissions of pulled files.
##
## Usage: fin pull-files

# Abort script if anything fails.
set -e

# Go to project root first

cd ${PROJECT_ROOT} || exit;

# Pull the files
echo "Pulling files from host..."
fin pull files -y

# Then head to the files folder

cd web/sites/default/files || exit;

for d in *; do
  if [ -d "$d" ]; then
    if [ $d != 'private' ] && [ $d != 'google_tag' ]; then
    echo "Setting default perms on $d";
    chmod -R 755 "$d";
    fi
  fi
done
